# Generated by Django 5.0.6 on 2024-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12, null=True),
        ),
    ]
